### ISSUE TITLE
setFullscreen is not a function

### ISSUE THREAD

**Issue by vorg** [szymonkaliski/Neutron#1]
Code

```javascript
var neutron = require('neutron');
neutron.openDevTools() 
console.log(neutron.getPosition())
neutron.setFullScreen(true)
```

Uploading an image as I can't copy from the console output...

<img width="433" alt="screen shot 2017-07-12 at 13 38 53" src="https://user-images.githubusercontent.com/171001/28118016-7931b552-6707-11e7-89c8-18e3d08d2d8b.png">

**Comment by szymonkaliski** [comment]
good catch, will fix shortly

**Comment by szymonkaliski** [comment]
should be fixed here: https://github.com/szymonkaliski/Neutron/releases/tag/v0.0.4 (`setFullScreen`, `isFullScreen`)
